FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /app
ENV ASPNETCORE_URLS="http://+:80" \
    ASPNETCORE_ENVIRONMENT="DockerDev"

COPY *.sln .
COPY aspnetapp/*.csproj ./aspnetapp/
RUN dotnet restore

COPY . .

WORKDIR /app/aspnetapp/
RUN dotnet build
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
